import type { ThemeData } from '../types'
import { brightAnsiHex, brightWhiteHex } from '../utils'

export function serializeAsGhostty(data: ThemeData): string {
  const { semanticColors: c, isDarkMode, displayName } = data

  const bright = (hex: string, isBlack = false) => brightAnsiHex(hex, isDarkMode, isBlack)

  // Strip any alpha suffix — Ghostty uses plain #RRGGBB
  const hex = (h: string) => h.slice(0, 7).toUpperCase()

  const palette: [number, string][] = [
    [0, c.terminalAnsiBlack.hex],
    [1, c.terminalAnsiRed.hex],
    [2, c.terminalAnsiGreen.hex],
    [3, c.terminalAnsiYellow.hex],
    [4, c.terminalAnsiBlue.hex],
    [5, c.terminalAnsiMagenta.hex],
    [6, c.terminalAnsiCyan.hex],
    [7, c.terminalAnsiWhite.hex],
    [8, bright(c.terminalAnsiBlack.hex, true)],
    [9, bright(c.terminalAnsiRed.hex)],
    [10, bright(c.terminalAnsiGreen.hex)],
    [11, bright(c.terminalAnsiYellow.hex)],
    [12, bright(c.terminalAnsiBlue.hex)],
    [13, bright(c.terminalAnsiMagenta.hex)],
    [14, bright(c.terminalAnsiCyan.hex)],
    // Bright white (15) lifts a step above white (7) so bold/bright text registers —
    // matching Tokyo Night / Gruvbox / Dracula, where 15 is brighter than 7. Audit note 2.
    [15, brightWhiteHex(c.terminalAnsiWhite.hex, isDarkMode)],
  ]

  const lines: string[] = [
    `# ${displayName}`,
    `# Generated by color-palette-pro`,
    '',
    `background = ${hex(c.editorBackground.hex)}`,
    `foreground = ${hex(c.editorForeground.hex)}`,
    `cursor-color = ${hex(c.cursorColor.hex)}`,
    // Selection reuses the UI primary-container pair — a soft branded background with a
    // contrast-checked on-color — instead of compositing the focus colour at peak alpha,
    // which left a light-on-light wash (~1.9:1). The container is L 0.30 dark / 0.90 light,
    // pairing with its on-color at ~10:1 (dark) / ~14:1 (light) — well clear of the wash and
    // in/above the popular-theme range (7.3–10.7). Audit note 1.
    `selection-background = ${hex(c.primaryContainer.hex)}`,
    `selection-foreground = ${hex(c.onPrimaryContainer.hex)}`,
    '',
    ...palette.map(([i, v]) => `palette = ${i}=${hex(v)}`),
  ]

  return lines.join('\n')
}
