import Color from 'colorjs.io'
import type { ThemeData } from '../types'
import { brightAnsiHex, toHex } from '../utils'

export function serializeAsGhostty(data: ThemeData): string {
  const { semanticColors: c, isDarkMode, displayName } = data

  const bright = (hex: string, isBlack = false) => brightAnsiHex(hex, isDarkMode, isBlack)

  // Strip any alpha suffix — Ghostty uses plain #RRGGBB
  const hex = (h: string) => h.slice(0, 7).toUpperCase()

  // Ghostty can't render a translucent selection, so a full-opacity focus color would erase
  // the selected text. Composite the focus color over the editor bg at the same legible alpha
  // the alpha-aware formats use, baking a solid hex that keeps selection-foreground readable.
  // (Audit 4G.)
  const selectionBg = toHex(
    new Color(c.editorBackground.hex).mix(new Color(c.focusBorder.hex), data.peakAlpha, {
      space: 'srgb',
      outputSpace: 'srgb',
    }) as Color,
  )

  const palette: [number, string][] = [
    [0, c.terminalAnsiBlack.hex],
    [1, c.terminalAnsiRed.hex],
    [2, c.terminalAnsiGreen.hex],
    [3, c.terminalAnsiYellow.hex],
    [4, c.terminalAnsiBlue.hex],
    [5, c.terminalAnsiMagenta.hex],
    [6, c.terminalAnsiCyan.hex],
    [7, c.terminalAnsiWhite.hex],
    [8, bright(c.terminalAnsiBlack.hex, true)],
    [9, bright(c.terminalAnsiRed.hex)],
    [10, bright(c.terminalAnsiGreen.hex)],
    [11, bright(c.terminalAnsiYellow.hex)],
    [12, bright(c.terminalAnsiBlue.hex)],
    [13, bright(c.terminalAnsiMagenta.hex)],
    [14, bright(c.terminalAnsiCyan.hex)],
    [15, c.editorForeground.hex],
  ]

  const lines: string[] = [
    `# ${displayName}`,
    `# Generated by color-palette-pro`,
    '',
    `background = ${hex(c.editorBackground.hex)}`,
    `foreground = ${hex(c.editorForeground.hex)}`,
    `cursor-color = ${hex(c.cursorColor.hex)}`,
    `selection-background = ${hex(selectionBg)}`,
    `selection-foreground = ${hex(c.editorForeground.hex)}`,
    '',
    ...palette.map(([i, v]) => `palette = ${i}=${hex(v)}`),
  ]

  return lines.join('\n')
}
